repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format .
        language: system
        files: \.py$
        pass: true

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check .
        language: system
        files: \.py$
        pass: false
